In [38]:
import pandas as pd
import numpy as np
import openpyxl
import sys
sys.path.append('../')
from src import sp_eda as se

pd.set_option('display.max_columns', None)

### Insertamos los datos del csv

In [39]:

df_acc = pd.read_csv('../data/raw/US_Accidents_March23.csv', low_memory=False)
print("Registros totales de accidentes:", len(df_acc))

df_weather = pd.read_csv('../data/raw/WeatherEvents_Jan2016-Dec2022.csv', low_memory=False)
print("Registros de eventos meteorologicos", len(df_weather))

Registros totales de accidentes: 7728394
Registros de eventos meteorologicos 8627181

Nos quedamos con aquellos del año 2022

In [40]:
y=2022
df_acc["Start_Time"] = pd.to_datetime(df_acc["Start_Time"], errors="coerce")
df_acc_year = df_acc[df_acc["Start_Time"].dt.year.isin([y])]

print(f"Registros de accidentes {y}:", len(df_acc_year))

df_weather["StartTime(UTC)"] = pd.to_datetime(df_weather["StartTime(UTC)"], errors="coerce")
df_weather_year = df_weather[df_weather["StartTime(UTC)"].dt.year.isin([y])]

print(f"Registros de eventos meteorologicos {y}:", len(df_weather_year))

Registros de accidentes 2022: 1268806
Registros de eventos meteorologicos 2022: 1147630

In [41]:
se.eda_prelim(df_weather_year)
df_weather_year.sample(5)

----------
DIMENSIONES
El conjunto de datos presenta 1147630 filas y 14 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.DataFrame'>
Index: 1147630 entries, 2228 to 8627180
Data columns (total 14 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   EventId            1147630 non-null  str
 1   Type               1147630 non-null  str
 2   Severity           1147630 non-null  str
 3   StartTime(UTC)     1147630 non-null  datetime64[us]
 4   EndTime(UTC)       1147630 non-null  str
 5   Precipitation(in)  1147630 non-null  float64
 6   TimeZone           1147630 non-null  str
 7   AirportCode        1147630 non-null  str
 8   LocationLat        1147630 non-null  float64
 9   LocationLng        1147630 non-null  float64
 10  City               1145281 non-null  str
 11  County             1147630 non-null  str
 12  State              1147630 non-null  str
 13  ZipCode            1137670 non-null  float64
dtypes: datetime64[us](1), float64(4), str(9)
memory usage: 131.3 MB
----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS
EventId              0.000000
Type                 0.000000
Severity             0.000000
StartTime(UTC)       0.000000
EndTime(UTC)         0.000000
Precipitation(in)    0.000000
TimeZone             0.000000
AirportCode          0.000000
LocationLat          0.000000
LocationLng          0.000000
City                 0.204683
County               0.000000
State                0.000000
ZipCode              0.867876
dtype: float64
----------
FRECUENCIA CATEGORÍAS
EventId
W-2229       1
W-2230       1
W-2231       1
W-2232       1
W-2233       1
            ..
W-9091890    1
W-9091891    1
W-9091892    1
W-9091893    1
W-9091894    1
Name: count, Length: 1147630, dtype: int64
-----------
Type
Rain             603152
Fog              291353
Snow             178062
Cold              34414
Precipitation     28349
Storm             12113
Hail                187
Name: count, dtype: int64
-----------
Severity
Light       660343
Severe      268815
Moderate    165045
UNK          28349
Heavy        24891
Other          187
Name: count, dtype: int64
-----------
EndTime(UTC)
2022-12-15 06:15:00    91
2022-12-22 20:55:00    82
2022-12-15 09:15:00    81
2022-12-15 08:15:00    80
2022-11-30 11:15:00    77
                       ..
2022-12-19 08:00:00     1
2022-12-19 09:40:00     1
2022-12-20 16:20:00     1
2022-12-29 16:00:00     1
2022-07-04 23:00:00     1
Name: count, Length: 297716, dtype: int64
-----------
TimeZone
US/Eastern     462844
US/Central     461556
US/Mountain    112582
US/Pacific     110648
Name: count, dtype: int64
-----------
AirportCode
KMLP    2260
K3TH    2260
KDWX    2250
KCEC    1896
KUIL    1816
        ...
KLHM       8
KCQV       6
KREO       5
K4HV       3
KFZG       1
Name: count, Length: 2046, dtype: int64
-----------
City
Jacksonville     4599
Washington       4570
Columbus         4259
Cleveland        4031
Greenville       3998
                 ...
Dryden              8
Colville            6
Jordan Valley       5
Hanksville          3
Fitzgerald          1
Name: count, Length: 1699, dtype: int64
-----------
County
Lincoln       11273
Washington    11010
Montgomery    10379
Jefferson      9802
Marion         8093
              ...
Box Elder        14
Erath            14
Eureka           12
Terrell           8
Ben Hill          1
Name: count, Length: 1094, dtype: int64
-----------
State
MN    68318
TX    67020
MI    60205
FL    47714
NC    47309
CA    42225
WI    42045
GA    38285
VA    36002
IL    35571
WA    33981
IA    32066
PA    30253
OH    30171
NY    28777
OR    26875
ND    25736
SC    25521
AL    25039
WY    24953
LA    24570
CO    23671
OK    22585
AR    21785
IN    21612
MO    17899
MS    17827
KY    17792
MA    17490
NE    16005
WV    14639
MT    14280
ID    13901
KS    13839
ME    13432
SD    12437
TN    11914
NM    11871
MD    10822
NH    10681
NJ     9683
AZ     8605
VT     7764
CT     7585
UT     5941
NV     4617
RI     3851
DE     2466
Name: count, dtype: int64
-----------

,EventId,Type,Severity,StartTime(UTC),EndTime(UTC),Precipitation(in),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode
4838619,W-5101748,Rain,Moderate,2022-02-22 22:53:00,2022-02-23 00:14:00,0.48,US/Eastern,KRME,43.2338,-75.4070,Rome,Oneida,NY,13441.0
7621292,W-8031199,Rain,Moderate,2022-06-11 10:23:00,2022-06-11 11:05:00,0.56,US/Pacific,KLWS,46.3745,-117.0154,Lewiston,Nez Perce,ID,83501.0
4210485,W-4439302,Snow,Light,2022-01-28 02:56:00,2022-01-28 03:56:00,0.00,US/Eastern,KUCP,41.0254,-80.4134,New Castle,Lawrence,PA,16101.0
690670,W-728437,Fog,Severe,2022-01-02 12:10:00,2022-01-02 12:49:00,0.00,US/Eastern,KORE,42.5700,-72.2869,Orange,Franklin,MA,1364.0
1218072,W-1285211,Rain,Light,2022-10-24 10:55:00,2022-10-24 12:55:00,0.00,US/Central,KDUC,34.4778,-97.9616,Duncan,Stephens,OK,73533.0

In [42]:
se.eda_prelim(df_acc_year)
df_acc_year.sample(5)

----------
DIMENSIONES
El conjunto de datos presenta 1268806 filas y 46 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.DataFrame'>
Index: 1268806 entries, 512217 to 5421634
Data columns (total 46 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   ID                     1268806 non-null  str
 1   Source                 1268806 non-null  str
 2   Severity               1268806 non-null  int64
 3   Start_Time             1268806 non-null  datetime64[us]
 4   End_Time               1268806 non-null  str
 5   Start_Lat              1268806 non-null  float64
 6   Start_Lng              1268806 non-null  float64
 7   End_Lat                1032624 non-null  float64
 8   End_Lng                1032624 non-null  float64
 9   Distance(mi)           1268806 non-null  float64
 10  Description            1268806 non-null  str
 11  Street                 1263351 non-null  str
 12  City                   1268763 non-null  str
 13  County                 1268806 non-null  str
 14  State                  1268806 non-null  str
 15  Zipcode                1268612 non-null  str
 16  Country                1268806 non-null  str
 17  Timezone               1267792 non-null  str
 18  Airport_Code           1263939 non-null  str
 19  Weather_Timestamp      1248106 non-null  str
 20  Temperature(F)         1241574 non-null  float64
 21  Wind_Chill(F)          1230424 non-null  float64
 22  Humidity(%)            1239829 non-null  float64
 23  Pressure(in)           1245552 non-null  float64
 24  Visibility(mi)         1239342 non-null  float64
 25  Wind_Direction         1234785 non-null  str
 26  Wind_Speed(mph)        1234791 non-null  float64
 27  Precipitation(in)      1223029 non-null  float64
 28  Weather_Condition      1241709 non-null  str
 29  Amenity                1268806 non-null  bool
 30  Bump                   1268806 non-null  bool
 31  Crossing               1268806 non-null  bool
 32  Give_Way               1268806 non-null  bool
 33  Junction               1268806 non-null  bool
 34  No_Exit                1268806 non-null  bool
 35  Railway                1268806 non-null  bool
 36  Roundabout             1268806 non-null  bool
 37  Station                1268806 non-null  bool
 38  Stop                   1268806 non-null  bool
 39  Traffic_Calming        1268806 non-null  bool
 40  Traffic_Signal         1268806 non-null  bool
 41  Turning_Loop           1268806 non-null  bool
 42  Sunrise_Sunset         1258177 non-null  str
 43  Civil_Twilight         1258177 non-null  str
 44  Nautical_Twilight      1258177 non-null  str
 45  Astronomical_Twilight  1258177 non-null  str
dtypes: bool(13), datetime64[us](1), float64(12), int64(1), str(19)
memory usage: 344.9 MB
----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS
ID                        0.000000
Source                    0.000000
Severity                  0.000000
Start_Time                0.000000
End_Time                  0.000000
Start_Lat                 0.000000
Start_Lng                 0.000000
End_Lat                  18.614508
End_Lng                  18.614508
Distance(mi)              0.000000
Description               0.000000
Street                    0.429932
City                      0.003389
County                    0.000000
State                     0.000000
Zipcode                   0.015290
Country                   0.000000
Timezone                  0.079918
Airport_Code              0.383589
Weather_Timestamp         1.631455
Temperature(F)            2.146270
Wind_Chill(F)             3.025049
Humidity(%)               2.283801
Pressure(in)              1.832747
Visibility(mi)            2.322183
Wind_Direction            2.681340
Wind_Speed(mph)           2.680867
Precipitation(in)         3.607880
Weather_Condition         2.135630
Amenity                   0.000000
Bump                      0.000000
Crossing                  0.000000
Give_Way                  0.000000
Junction                  0.000000
No_Exit                   0.000000
Railway                   0.000000
Roundabout                0.000000
Station                   0.000000
Stop                      0.000000
Traffic_Calming           0.000000
Traffic_Signal            0.000000
Turning_Loop              0.000000
Sunrise_Sunset            0.837717
Civil_Twilight            0.837717
Nautical_Twilight         0.837717
Astronomical_Twilight     0.837717
dtype: float64
----------
FRECUENCIA CATEGORÍAS
ID
A-512230     1
A-512231     1
A-512232     1
A-512233     1
A-512234     1
            ..
A-5462838    1
A-5462839    1
A-5462840    1
A-5462841    1
A-5462842    1
Name: count, Length: 1268806, dtype: int64
-----------
Source
Source1    1032624
Source2     219411
Source3      16771
Name: count, dtype: int64
-----------
End_Time
2022-08-18 13:45:00    31
2022-12-22 20:45:00    28
2022-01-05 13:59:00    27
2022-08-04 14:28:11    27
2022-07-29 08:51:46    26
                       ..
2022-09-16 17:15:58     1
2022-01-17 15:28:05     1
2022-12-01 20:39:50     1
2022-05-20 17:20:36     1
2022-02-01 16:43:36     1
Name: count, Length: 1022891, dtype: int64
-----------
Description
Accident                                                                                                                          2800
A crash has occurred causing no to minimum delays. Use caution.                                                                   2132
An unconfirmed report of a crash has been received. Use caution.                                                                  1301
A crash has occurred with minimal delay to traffic. Prepare to slow or move over for worker safety.                                934
A crash has occurred use caution.                                                                                                  687
                                                                                                                                  ...
Slow traffic on I-70 W - CO-9 S - US-6 W from US-6/Exit 216 (I-70) to CR-16/Shrine Pass Rd/Exit 190 (I-70) due to accident.          1
Accident from W 400 S to I-15 N.                                                                                                     1
Stationary traffic on FL-869 N from FL-834/Sample Rd/Exit 8 (FL-869) to US-441/Exit 15 (FL-869) due to accident.                     1
Slow traffic on Wilbur Cross Pkwy N - CT-15 N from CT-150/Hall Ave/Exit 65 (CT-15) to I-691/Exit 68 W (CT-15) due to accident.       1
Stationary traffic on US-29 N - NC-49 from Honduras Dr to W Craighead Rd due to accident.                                            1
Name: count, Length: 781102, dtype: int64
-----------
Street
I-95 S               11996
I-95 N               11051
I-95                  9306
I-5 N                 8000
I-10 E                7548
                     ...
 Rebecca Rd              1
E Tonopah Dr             1
 Statesville Blvd        1
Line Creek Trl           1
 NW 114th Way            1
Name: count, Length: 143467, dtype: int64
-----------
City
Miami          44223
Orlando        25309
Los Angeles    22220
Houston        19407
Dallas         18256
               ...
Whiting            1
Westerlo           1
Boyd               1
Kresgeville        1
Parkston           1
Name: count, Length: 10171, dtype: int64
-----------
County
Los Angeles    73976
Miami-Dade     61696
Orange         47292
Dallas         22695
Montgomery     21511
               ...
Atchison           1
Doniphan           1
Bosque             1
St. Bernard        1
Tom Green          1
Name: count, Length: 1634, dtype: int64
-----------
State
CA    266275
FL    186101
TX     71725
VA     69801
NY     66498
SC     63161
PA     57583
NC     53044
NJ     29943
AZ     28176
TN     28039
MN     26514
MD     26034
GA     24509
LA     24488
MI     21005
OR     20579
OH     20338
IL     19463
AL     16719
CO     15222
MO     14291
CT     14288
UT     12590
WA     11567
IN     10641
MT      9631
OK      7273
AR      6513
MA      6005
WI      5661
DC      4893
KS      4611
WV      3610
IA      3521
NV      3131
MS      2569
KY      2426
DE      2299
ID      1553
WY      1389
RI      1374
NM      1162
NE      1132
ND       821
NH       474
ME       105
VT        37
SD        22
Name: count, dtype: int64
-----------
Zipcode
33186         1962
32819         1875
91761         1511
32837         1397
92407         1375
              ...
33178-1177       1
23060-6215       1
75702-8413       1
94303-4622       1
23669-2307       1
Name: count, Length: 244692, dtype: int64
-----------
Country
US    1268806
Name: count, dtype: int64
-----------
Timezone
US/Eastern     662326
US/Pacific     305728
US/Central     228388
US/Mountain     71350
NaN              1014
Name: count, dtype: int64
-----------
Airport_Code
KMIA    19298
KOPF    18090
KCQT    16978
KORL    16221
KRDU    15475
        ...
KPDC        1
KSMN        1
KSZT        1
KSJT        1
KMHE        1
Name: count, Length: 1903, dtype: int64
-----------
Weather_Timestamp
NaN                    20700
2022-03-13 01:53:00      951
2022-05-13 16:53:00      384
2022-03-13 01:55:00      372
2022-05-17 15:53:00      368
                       ...
2022-12-27 22:22:00        1
2022-10-03 18:23:00        1
2022-04-12 06:19:00        1
2022-05-24 23:54:00        1
2022-12-01 19:34:00        1
Name: count, Length: 133984, dtype: int64
-----------
Wind_Direction
CALM    202181
S       100138
W        90751
N        69785
E        65360
SSW      63899
VAR      63018
WNW      62798
NW       60851
SW       60305
WSW      59019
SSE      56564
NNW      54877
SE       49964
ESE      47697
ENE      43182
NE       42973
NNE      41423
NaN      34021
Name: count, dtype: int64
-----------
Weather_Condition
Fair                           623334
Mostly Cloudy                  164747
Cloudy                         162841
Partly Cloudy                  114422
Light Rain                      48874
                                ...
Squalls                             2
Heavy Freezing Rain / Windy         1
Heavy Freezing Drizzle              1
Sand / Dust Whirls Nearby           1
Thunder and Hail / Windy            1
Name: count, Length: 91, dtype: int64
-----------
Sunrise_Sunset
Day      906365
Night    351812
NaN       10629
Name: count, dtype: int64
-----------
Civil_Twilight
Day      960762
Night    297415
NaN       10629
Name: count, dtype: int64
-----------
Nautical_Twilight
Day      1019479
Night     238698
NaN        10629
Name: count, dtype: int64
-----------
Astronomical_Twilight
Day      1065999
Night     192178
NaN        10629
Name: count, dtype: int64
-----------

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Street,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
4538263,A-4572645,Source1,2,2022-07-30 09:31:00,2022-07-30 09:52:30,33.305705,-111.896654,33.305805,-111.893602,0.176,Stationary traffic on W Chandler Blvd from McC...,W Chandler Blvd,Chandler,Maricopa,AZ,85226-4935,US,US/Mountain,KCHD,2022-07-30 09:47:00,90.0,90.0,49.0,28.65,10.0,VAR,5.0,NaN,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
4688608,A-4724193,Source1,2,2022-10-10 21:40:30,2022-10-10 23:46:25,38.034195,-78.859814,38.034188,-78.859960,0.008,On US-250 in the County of Augusta in the vici...,Three Notched Mountain Hwy,Waynesboro,Augusta,VA,22980,US,US/Eastern,KSHD,2022-10-10 21:35:00,44.0,44.0,84.0,29.03,10.0,CALM,0.0,0.0,Fair,False,False,False,False,False,False,False,False,False,True,False,False,False,Night,Night,Night,Night
729491,A-739187,Source2,2,2022-01-21 15:59:01,2022-01-21 16:43:49,34.162430,-86.836212,NaN,NaN,0.000,Lane blocked due to accident on US-31 2nd Ave ...,2nd Ave SW,Cullman,Cullman,AL,35055-5311,US,US/Central,K3A1,2022-01-21 15:53:00,31.0,21.0,67.0,29.68,10.0,NNE,13.0,0.0,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
4565942,A-4600584,Source1,2,2022-12-28 14:16:32,2022-12-28 18:25:10,41.822663,-72.666105,41.804069,-72.658713,1.340,Stationary traffic on I-91 S from CT-178/Park ...,I-91 S,Windsor,Hartford,CT,06095,US,US/Eastern,KBDL,2022-12-28 13:51:00,46.0,40.0,34.0,30.01,10.0,S,15.0,0.0,Mostly Cloudy,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
4425132,A-4458649,Source1,2,2022-05-12 01:23:24,2022-05-12 03:19:14,34.802681,-82.280717,34.808568,-82.284744,0.467,Incident on I-385 NB near EXIT 34 Road closed....,Golden Strip Fwy N,Greenville,Greenville,SC,29607,US,US/Eastern,KGMU,2022-05-12 00:53:00,65.0,65.0,56.0,29.03,10.0,N,8.0,0.0,Fair,False,False,False,False,True,False,False,False,False,False,False,False,False,Night,Night,Night,Night

###  Combinación del dataframe Accidentes con dataframe de Eventos meteorológicos.
Se ha decidido agrupar los accidentes y eventos por estado y día del suceso.
Además se va a añadir los subtotales del grado de severidad de accidente. Lo mismo se va a hacer con el dataframe de eventos meteorologicos, manteniendo subtotales de severidad meteorologica y tipo de evento evento meteorologico.

Se crea la columna date de ambos dataframe

In [43]:
df_acc_year["Date"] = df_acc_year["Start_Time"].dt.date
df_weather_year["Date"] = df_weather_year["StartTime(UTC)"].dt.date

Contamos los eventos meteorologicos por estado y día.

In [44]:
weather_tot_events = (
    df_weather_year
    .groupby(["State", "Date"])
    .size()
    .reset_index(name="weather_events")
)

Añadimos cuenta con el tipo de evento meteorologico

In [45]:
weather_by_type = (
    df_weather_year
    .groupby(["State","Date", "Type"])
    .size()
    .unstack(fill_value=0)
    .add_prefix("typ_")
    .reset_index()
)

Añadimos cuenta con la severidad

In [46]:
weather_by_severity = (
    df_weather_year
    .groupby(["State", "Date", "Severity"])
    .size()
    .unstack(fill_value=0)
    .add_prefix("wea_sev_")
    .reset_index()
)

Lo unificamos todo en un data frame

In [47]:
weather_agg = (
    weather_tot_events
    .merge(weather_by_type, on=["State", "Date"], how="left")
    .merge(weather_by_severity, on=["State", "Date"], how="left")
)

In [48]:
se.eda_prelim(weather_agg)
weather_agg.sample(5)

----------
DIMENSIONES
El conjunto de datos presenta 16714 filas y 16 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.DataFrame'>
RangeIndex: 16714 entries, 0 to 16713
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              16714 non-null  str
 1   Date               16714 non-null  object
 2   weather_events     16714 non-null  int64
 3   typ_Cold           16714 non-null  int64
 4   typ_Fog            16714 non-null  int64
 5   typ_Hail           16714 non-null  int64
 6   typ_Precipitation  16714 non-null  int64
 7   typ_Rain           16714 non-null  int64
 8   typ_Snow           16714 non-null  int64
 9   typ_Storm          16714 non-null  int64
 10  wea_sev_Heavy      16714 non-null  int64
 11  wea_sev_Light      16714 non-null  int64
 12  wea_sev_Moderate   16714 non-null  int64
 13  wea_sev_Other      16714 non-null  int64
 14  wea_sev_Severe     16714 non-null  int64
 15  wea_sev_UNK        16714 non-null  int64
dtypes: int64(14), object(1), str(1)
memory usage: 2.0+ MB
----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS
State                0.0
Date                 0.0
weather_events       0.0
typ_Cold             0.0
typ_Fog              0.0
typ_Hail             0.0
typ_Precipitation    0.0
typ_Rain             0.0
typ_Snow             0.0
typ_Storm            0.0
wea_sev_Heavy        0.0
wea_sev_Light        0.0
wea_sev_Moderate     0.0
wea_sev_Other        0.0
wea_sev_Severe       0.0
wea_sev_UNK          0.0
dtype: float64
----------
FRECUENCIA CATEGORÍAS
State
CA    365
FL    365
MI    365
OR    365
TX    365
WA    365
WI    365
GA    364
MN    364
NC    364
ND    364
LA    362
MS    362
NY    362
OH    362
PA    362
CT    361
AL    360
IA    360
ID    360
IL    360
VA    360
WY    359
SC    358
CO    357
MT    357
OK    357
AR    356
IN    354
MO    352
NH    351
TN    351
WV    351
ME    349
MA    347
MD    346
NM    346
NE    344
KY    342
KS    341
VT    339
SD    338
AZ    335
UT    314
NJ    310
NV    287
RI    254
DE    237
Name: count, dtype: int64
-----------
Date
2022-01-01    48
2022-01-20    48
2022-02-02    48
2022-02-22    48
2022-02-23    48
              ..
2022-04-25    40
2022-11-23    40
2022-02-27    38
2022-02-20    37
2022-03-13    31
Name: count, Length: 365, dtype: int64
-----------

,State,Date,weather_events,typ_Cold,typ_Fog,typ_Hail,typ_Precipitation,typ_Rain,typ_Snow,typ_Storm,wea_sev_Heavy,wea_sev_Light,wea_sev_Moderate,wea_sev_Other,wea_sev_Severe,wea_sev_UNK
1792,CT,2022-01-20,32,2,1,0,0,10,19,0,0,23,6,0,3,0
9781,NH,2022-10-25,96,3,63,0,0,28,0,2,0,27,3,0,66,0
12907,SC,2022-03-02,26,4,22,0,0,0,0,0,0,0,4,0,22,0
7121,MN,2022-05-17,129,2,15,0,1,111,0,0,0,105,13,0,10,1
7202,MN,2022-08-06,493,2,9,0,43,438,0,1,17,378,43,0,12,43

Vamos a agrupar el numero total de accidentes por día y estado añadiendo el subtotal segun la severidad del accidente.

In [49]:
acc_tot = (
    df_acc_year
    .groupby(["State", "Date"])
    .size()
    .reset_index(name="acc_events"))

In [50]:
acc_by_severity = (
    df_acc_year
    .groupby(["State", "Date", "Severity"])
    .size()
    .unstack(fill_value=0)
    .add_prefix("acc_sev_")
    .reset_index())

Unimos ambos

In [51]:
acc_agg = (
    acc_tot
    .merge(acc_by_severity, on=["State", "Date"], how="left")
)

In [52]:
se.eda_prelim(acc_agg)
acc_agg.sample(5)

----------
DIMENSIONES
El conjunto de datos presenta 14431 filas y 7 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.DataFrame'>
RangeIndex: 14431 entries, 0 to 14430
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   State       14431 non-null  str
 1   Date        14431 non-null  object
 2   acc_events  14431 non-null  int64
 3   acc_sev_1   14431 non-null  int64
 4   acc_sev_2   14431 non-null  int64
 5   acc_sev_3   14431 non-null  int64
 6   acc_sev_4   14431 non-null  int64
dtypes: int64(5), object(1), str(1)
memory usage: 789.3+ KB
----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS
State         0.0
Date          0.0
acc_events    0.0
acc_sev_1     0.0
acc_sev_2     0.0
acc_sev_3     0.0
acc_sev_4     0.0
dtype: float64
----------
FRECUENCIA CATEGORÍAS
State
SC    341
LA    336
NY    336
OR    335
WA    335
AZ    334
CA    334
MI    334
MN    334
NC    334
FL    333
GA    333
NJ    333
TX    333
AL    332
CO    332
CT    332
MO    332
MT    332
PA    332
TN    332
UT    332
VA    332
IL    331
IN    331
MD    331
OK    331
AR    330
DC    329
WV    326
KS    324
NV    324
IA    322
DE    319
WI    319
OH    305
MS    299
RI    283
KY    277
MA    274
ID    250
NE    247
NM    245
ND    203
WY    190
NH    160
ME     70
VT     32
SD      6
Name: count, dtype: int64
-----------
Date
2022-02-03    48
2022-01-12    47
2022-01-14    47
2022-01-21    47
2022-01-24    47
              ..
2022-05-08     1
2022-05-09     1
2022-10-21     1
2022-10-29     1
2022-03-28     1
Name: count, Length: 348, dtype: int64
-----------

,State,Date,acc_events,acc_sev_1,acc_sev_2,acc_sev_3,acc_sev_4
5340,LA,2022-07-30,41,0,34,7,0
5738,MA,2022-12-13,2,0,2,0,0
5448,LA,2022-12-01,97,0,97,0,0
12789,UT,2022-08-28,14,0,13,1,0
8511,NE,2022-09-22,2,0,2,0,0

Creamos nuestro dataframe final con el agregado de accidentes con eventos meteorologicos

In [53]:
df_final = acc_agg.merge(
    weather_agg,
    on=["State", "Date"],
    how="outer"
)

Se van a añadir los nombres de los estados de estados unidos para tener más claro los datos

In [54]:
df_states = pd.read_csv('../data/raw/United States - Region Codes.csv', low_memory=False)
df_states.sample(5)

      Region Region code                   Country
16    Kansas       us-ks  United States of America
15      Iowa       us-ia  United States of America
19     Maine       us-me  United States of America
5   Colorado       us-co  United States of America
36  Oklahoma       us-ok  United States of America

VAmos a cambiar los nombres de las columnas para hacer el merge y a estandarizar los registros de los codigos de estado con el fin de hacerlos conicidir con el df_final poniendolos en mayúsculas y eliminando el "US-"

In [55]:
df_states= df_states.rename(columns={"Region code": "State","Region":"Name"})
df_states["State"] = df_states["State"].str.upper()
df_states["State"] = df_states["State"].str.replace("US-", "", regex=False)
df_states.sample(5)

                    Name State                   Country
32              New York    NY  United States of America
34          North Dakota    ND  United States of America
8   District of Columbia    DC  United States of America
35                  Ohio    OH  United States of America
40        South Carolina    SC  United States of America

Introducimos en nuestro df_final el nombre del estado para una mayor comprension de los datos

In [56]:
df_final = df_final.merge(
    df_states[["State", "Name"]],
    on="State",
    how="left")

In [57]:
se.eda_prelim(df_final)

----------
DIMENSIONES
El conjunto de datos presenta 17653 filas y 22 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.DataFrame'>
RangeIndex: 17653 entries, 0 to 17652
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              17653 non-null  str
 1   Date               17653 non-null  object
 2   acc_events         14431 non-null  float64
 3   acc_sev_1          14431 non-null  float64
 4   acc_sev_2          14431 non-null  float64
 5   acc_sev_3          14431 non-null  float64
 6   acc_sev_4          14431 non-null  float64
 7   weather_events     16714 non-null  float64
 8   typ_Cold           16714 non-null  float64
 9   typ_Fog            16714 non-null  float64
 10  typ_Hail           16714 non-null  float64
 11  typ_Precipitation  16714 non-null  float64
 12  typ_Rain           16714 non-null  float64
 13  typ_Snow           16714 non-null  float64
 14  typ_Storm          16714 non-null  float64
 15  wea_sev_Heavy      16714 non-null  float64
 16  wea_sev_Light      16714 non-null  float64
 17  wea_sev_Moderate   16714 non-null  float64
 18  wea_sev_Other      16714 non-null  float64
 19  wea_sev_Severe     16714 non-null  float64
 20  wea_sev_UNK        16714 non-null  float64
 21  Name               17653 non-null  str
dtypes: float64(19), object(1), str(2)
memory usage: 3.0+ MB
----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS
State                 0.000000
Date                  0.000000
acc_events           18.251855
acc_sev_1            18.251855
acc_sev_2            18.251855
acc_sev_3            18.251855
acc_sev_4            18.251855
weather_events        5.319209
typ_Cold              5.319209
typ_Fog               5.319209
typ_Hail              5.319209
typ_Precipitation     5.319209
typ_Rain              5.319209
typ_Snow              5.319209
typ_Storm             5.319209
wea_sev_Heavy         5.319209
wea_sev_Light         5.319209
wea_sev_Moderate      5.319209
wea_sev_Other         5.319209
wea_sev_Severe        5.319209
wea_sev_UNK           5.319209
Name                  0.000000
dtype: float64
----------
FRECUENCIA CATEGORÍAS
State
CA    365
CT    365
FL    365
GA    365
IN    365
LA    365
MI    365
MS    365
NC    365
NY    365
OK    365
OR    365
PA    365
TX    365
VA    365
WA    365
WI    365
AL    364
AR    364
CO    364
MD    364
MN    364
MT    364
ND    364
OH    364
SC    364
WV    364
IA    363
IL    363
KS    363
MO    363
ID    362
MA    362
TN    362
WY    362
NJ    361
AZ    360
KY    360
NM    359
UT    359
NV    356
NH    355
NE    353
DE    350
ME    350
VT    340
SD    339
RI    337
DC    329
Name: count, dtype: int64
-----------
Date
2022-01-01    49
2022-01-03    49
2022-01-04    49
2022-01-05    49
2022-01-13    49
              ..
2022-03-28    43
2022-11-29    43
2022-10-20    42
2022-10-30    42
2022-03-27    40
Name: count, Length: 365, dtype: int64
-----------
Name
California              365
Connecticut             365
Florida                 365
Georgia                 365
Indiana                 365
Louisiana               365
Michigan                365
Mississippi             365
North Carolina          365
New York                365
Oklahoma                365
Oregon                  365
Pennsylvania            365
Texas                   365
Virginia                365
Washington              365
Wisconsin               365
Alabama                 364
Arkansas                364
Colorado                364
Maryland                364
Minnesota               364
Montana                 364
North Dakota            364
Ohio                    364
South Carolina          364
West Virginia           364
Iowa                    363
Illinois                363
Kansas                  363
Missouri                363
Idaho                   362
Massachusetts           362
Tennessee               362
Wyoming                 362
New Jersey              361
Arizona                 360
Kentucky                360
New Mexico              359
Utah                    359
Nevada                  356
New Hampshire           355
Nebraska                353
Delaware                350
Maine                   350
Vermont                 340
South Dakota            339
Rhode Island            337
District of Columbia    329
Name: count, dtype: int64
-----------

Guardamos nuestro nuevo archivo con ambos archivos juntos y pasamos a la limpieza

In [58]:
df_final.to_csv('../data/Acc_met.csv', index=False)